services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
    - /tmp/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
